### ISSUE TITLE
Without Object mode selected, the translate/scale tools don't work on non-chisel objects

### ISSUE THREAD

**Issue by jmickle66666666** [RadicalCSG/Chisel.Prototype#16]
If you select any tool other than Object tool, the gizmos for translating, scaling etc do not appear when selecting any non-CSG object, which is confusing can easily break flow.

The toolbox shouldn't affect how you handle anything outside of Chisel, or at the very least it should default back to Object mode when you select anything else.

**Comment by LogicalError** [comment]
Using EditorTools might fix this. See #125

**Comment by LogicalError** [comment]
Old, bug, this has already been fixed some time ago
