### ISSUE TITLE
Drawing shapes on brushes isn't consistent

### ISSUE THREAD

**Issue by otdavies** [RadicalCSG/Chisel.Prototype#18]
When drawing brushes (of all types it appears) will occasionally not register legal draw surfaces.

Example: 
![2019-03-07_01-37-52](https://user-images.githubusercontent.com/3145170/53946943-a5e54f80-4079-11e9-8fdf-9b585ff6b462.gif)

**Comment by LogicalError** [comment]
@otdavies could you send me that specific scene so I can verify when I've fixed this?

**Comment by otdavies** [comment]
Note: It appears that the editor camera's tilt has a lot to do with this issue. If you move the camera around and try many angles, some surfaces will become selectable that were bugged before.

**Comment by LogicalError** [comment]
This _might've_ been fixed already
