### ISSUE TITLE
Extrusion from existing brush face

### ISSUE THREAD

**Issue by otdavies** [RadicalCSG/Chisel.Prototype#19]
It would be beneficial to have an extrusion function similar to RealtimeCSG.

**Comment by LogicalError** [comment]
Yup, definitely should have this. Also extrusion from multiple surfaces at the same time

**Comment by jmickle66666666** [comment]
Would this be possible from generators? or should it be part of the normal brush editor (when it exists)

**Comment by LogicalError** [comment]
If we can query the generators for surfaces, or better; be able to basically get the surface data from the brushes generated by the generators ... then I see no reason why we couldn't extrude from generators just as easily as from brushes

**Comment by otdavies** [comment]
How hard would this be today? Is this domain specific knowledge independent enough for me to give it a go?
