### ISSUE TITLE
Editing duplicate of brush edits original as well

### ISSUE THREAD

**Issue by nukeandbeans** [RadicalCSG/Chisel.Prototype#2]
Duplicating any brush (CTRL + D) and editing the duplicate's size causes changes to the original brush to copy these changes in the visual mesh only.

**Comment by Kerfuffles** [comment]
#8

**Comment by LogicalError** [comment]
We have a duplicate ticket about a duplication bug ;p

I have a temporary fix (not uploaded). We should keep this ticket open until we've fixed it properly

**Comment by LogicalError** [comment]
Fix was only a temporary solution. Keeping this ticket open to make sure we don't forget about this

**Comment by Kerfuffles** [comment]
It appears this behavior no longer persists? Was this fixed?

**Comment by LogicalError** [comment]
It was fixed, but with a temporary solution? Just keeping this ticket to make sure it's revisited
