### ISSUE TITLE
Surface Editor

### ISSUE THREAD

**Issue by jmickle66666666** [RadicalCSG/Chisel.Prototype#20]
### Surface Editor Tool

* Modify texture offset, rotation and scale
* Apply materials quickly and easily
* Copy material and surface properties from one face to another
* Automatically UV of entire brush or selected faces based on worldspace coordinates and given scale
* Select default material for new brushes
* ["Follow Face"](https://raw.githubusercontent.com/wiki/sabresaurus/SabreCSG/images/brush-tools-face-10.gif) (Match UV offset for multiple faces by dragging over them)

Texture offset changes should be aligned to grid unless the Shift modifier is held. Rotation and scale should work the same too.

Offset/Rotate/Scale should honor the relevant selected tool in Unity
<img width="200" alt="screenshot 2019-03-07 11 09 57" src="https://user-images.githubusercontent.com/7083717/53949061-90981180-40c9-11e9-8617-408bf9aeed2e.png">

A list of recent/frequently used materials for easy selection, plus user-definable groups of materials to select from, with customizable previews (show Sphere, Plane, Cube preview etc, resize previews as in the unity Project window)

Ability to snap UVs to edges of the face and edges of the texture, and shear textures.

Some mockups should be created to plan the UI and features out and get a feel for what considerations may arise.

**Comment by LogicalError** [comment]
```[tasklist]
- [] Modify texture offset, rotation and scale
- [] Apply materials quickly and easily
- [] Copy material and surface properties from one face to another
- [] Automatically UV of entire brush or selected faces based on worldspace coordinates and given scale
- [] Select default material for new brushes
- [] ["Follow Face"](https://raw.githubusercontent.com/wiki/sabresaurus/SabreCSG/images/brush-tools-face-10.gif) (Match UV offset for multiple faces by dragging over them)
- [] Texture offset changes should be aligned to grid unless the Shift modifier is held. Rotation and scale should work the same too.
- [] Offset/Rotate/Scale should honor the relevant selected tool in Unity -> they have their own toolbuttons
- [] A list of recent/frequently used materials for easy selection, 
- [] plus user-definable groups of materials to select from, with customizable previews (show Sphere, Plane, Cube preview etc, resize previews as in the unity Project window)
```

**Comment by LogicalError** [comment]
I guess tasklists don't work as a comment ;p
I think I'm going to break up these suggestions into multiple tickets

**Comment by LogicalError** [comment]
Created tickets for all items that haven't been implemented yet, so closing ticket
