### ISSUE TITLE
Implement transform tool support 

### ISSUE THREAD

**Issue by LogicalError** [RadicalCSG/Chisel.Prototype#275]
Right now the transform tool mode (the one that does scale,rotate and translate in one) is not supported in Chisel, and we should support it

**Comment by vncastanheira** [comment]
https://user-images.githubusercontent.com/1210284/133323368-a2213135-a950-4f55-a048-a7c1bf0e48e0.mp4

It seems to recognize the transformations on a brush, what's the expected behaviour here?

**Comment by Kerfuffles** [comment]
He's talking about the combined transform tool with all 3 handles in one.

**Comment by Tyssim10** [comment]
Just tried the the "Transform tool" (as is its proper name). It is supported now and the issue can be marked as solved @LogicalError 

https://user-images.githubusercontent.com/1552114/133337278-fb8bcdac-7ebe-42b8-93ad-ba1188215c82.mp4

**Comment by Kerfuffles** [comment]
> Just tried the the "Transform tool" (as is its proper name). It is supported now and the issue can be marked as solved @LogicalError

Going to go ahead and close this. Thanks y'all.
