### ISSUE TITLE
PreviewRendererUtility error spams console when a brush is selected

### ISSUE THREAD

**Issue by Kerfuffles** [RadicalCSG/Chisel.Prototype#3]
`
A PreviewRenderUtility was not clean up properly before assembly reloading which lead to leaking this scene in the Editor. This can be caused by not calling Cleanup() during the OnDisable of an Editor or an EditorWindow.`
`
UnityEditor.PreviewRenderUtility:Finalize()
`

**Comment by LogicalError** [comment]
Fixed in #101
