### ISSUE TITLE
CSG operations are not applied

### ISSUE THREAD

**Issue by fLindahl** [RadicalCSG/Chisel.Prototype#335]
I'm running 2021.2.7f1 with Chisel at rev. 78e58ba

When trying to change brush operation in the property inspector, no matter the type of brush, nothing changes in the internal representation of the brush.
The CSG model is active.

However, if I go to the CSG history window, and undo+redo - the change is applied.

Here are some images:
![1](https://user-images.githubusercontent.com/18470258/147657977-55b18474-e8e8-410e-a1a2-993b391ec895.png)
![2](https://user-images.githubusercontent.com/18470258/147657925-0d4ecede-0a8d-490d-b0e2-0059d1c1d37d.png)
![3](https://user-images.githubusercontent.com/18470258/147657929-4641e495-2f43-4994-aae0-099b796a7de0.png)
![4](https://user-images.githubusercontent.com/18470258/147657987-26207c5e-1331-44cc-a381-71a0c40f191b.png)

**Comment by LogicalError** [comment]
Fixed in latest version
