### ISSUE TITLE
Is it possible to use this at runtime unlike realtime-csg?

### ISSUE THREAD

**Issue by imineti** [RadicalCSG/Chisel.Prototype#339]
Is it possible to use this at runtime unlike realtime-csg? Also is this still being worked on, there seem to be any recent activity #

**Comment by alexjhetherington** [comment]
1. It is possible to use at runtime
2. It is still being worked on, albeit slowly
3. It is not production ready

I recommend joining the discord if you want to stay updated.

**Comment by Kerfuffles** [comment]
A lot of backend work is being done in a another repo, until it is ready to be presented. The project is active, but a good bit of other things rely on that backend work to be ready, and it's being worked on in our free time. As @alexjhetherington said, it's recommended to join the discord to keep updated on things.
