### ISSUE TITLE
Warnings about using deprecated Prefab API

### ISSUE THREAD

**Issue by LogicalError** [RadicalCSG/Chisel.Prototype#4]
Packages\com.chisel.components\Chisel\Components\API.private\CSGNodeHierarchyManager.cs(865,11): warning CS0618: '**PrefabUtility.GetPrefabType(Object)' is obsolete: 'Use GetPrefabAssetType and GetPrefabInstanceStatus to get the full picture about Prefab types.**'

Packages\com.chisel.components\Chisel\Components\API.private\CSGNodeHierarchyManager.cs(865,65): warning CS0618: '**PrefabType' is obsolete: 'PrefabType no longer tells everything about Prefab instance.**'

Packages\com.chisel.editor\Chisel\Editor\Components\Containers\Model\Editor\CSGModelEditor.cs(267,16): warning CS0618: '**PrefabUtility.GetPrefabType(Object)' is obsolete: 'Use GetPrefabAssetType and GetPrefabInstanceStatus to get the full picture about Prefab types.**'

Packages\com.chisel.editor\Chisel\Editor\Components\Containers\Model\Editor\CSGModelEditor.cs(268,21): warning CS0618: '**PrefabType' is obsolete: 'PrefabType no longer tells everything about Prefab instance.**'

Packages\com.chisel.editor\Chisel\Editor\Components\Containers\Model\Editor\CSGModelEditor.cs(268,50): warning CS0618: '**PrefabType' is obsolete: 'PrefabType no longer tells everything about Prefab instance.**'

**Comment by jeffvella** [comment]
Related to PR #37

**Comment by Kerfuffles** [comment]
This has been fixed. Going to go ahead and close this issue.
See commit 87a5517
