### ISSUE TITLE
Isolate/Hide brushes

### ISSUE THREAD

**Issue by jmickle66666666** [RadicalCSG/Chisel.Prototype#41]
![hide](https://user-images.githubusercontent.com/7083717/54525148-d7142880-4973-11e9-8b15-97f617a0f538.gif)

Ability to hide or isolate specific brushes, very useful when working on complex scenes. 

Unity 2019 has visibility controls which would be best to use, but a solution would need to be made for 2018 if we support that too.

**Comment by LogicalError** [comment]
We should take advantage of the ability to hide/show gameobjects in the hierarchy in 2019.1 and beyond

**Comment by LogicalError** [comment]
This has already been implemented!
