### ISSUE TITLE
Can't use the Axis Gizmo when using a Generator

### ISSUE THREAD

**Issue by jmickle66666666** [RadicalCSG/Chisel.Prototype#66]
If you have any of the generators selected, clicking the unity axis gizmo (to switch perspective mode or move the view), it passes through and just draws the generator.

**Comment by LogicalError** [comment]
With axis gizmo, do you mean this thing?
![axis_gizmo](https://user-images.githubusercontent.com/157976/56134140-463e6600-5f8e-11e9-9420-17940969f03e.PNG)

**Comment by jmickle66666666** [comment]
yes

**Comment by LogicalError** [comment]
Selection doesn't seem to be important here. It's just that when we're in generator mode, the axis gizmo is not hoverable/clickable
