### ISSUE TITLE
Cylinder tool preview does not match generated radius

### ISSUE THREAD

**Issue by jmickle66666666** [RadicalCSG/Chisel.Prototype#7]
![cylinder](https://user-images.githubusercontent.com/7083717/53830501-e1512280-3f82-11e9-87ee-14e56f06bb12.gif)

**Comment by LogicalError** [comment]
I have a fix. Cylinder diameter was incorrect due to old code changing from "radius" to "diameter" .. and certain values should've been multiplied by 2

**Comment by LogicalError** [comment]
Fix has not been uploaded yet, so I'll leave this ticket open until I've uploaded it.

**Comment by LogicalError** [comment]
Fixed!
