### ISSUE TITLE
Cylinder resizing only shrinks

### ISSUE THREAD

**Issue by jmickle66666666** [RadicalCSG/Chisel.Prototype#9]
![interesting](https://user-images.githubusercontent.com/7083717/53830789-81a74700-3f83-11e9-8347-ae4d64f1dadb.gif)

**Comment by LogicalError** [comment]
I have a fix, it turned out that the diameter of the cylinder was converted into a radius (diameter*0.5) to be used for the handles .. and then when the handles moved, it wasn't multiplied by 2 when fed back into the cylinder definition. so each tiny move would half the cylinder diameter. oops.

**Comment by LogicalError** [comment]
Fix has not been uploaded yet, so I'll leave this ticket open until I've uploaded it.

**Comment by LogicalError** [comment]
Fixed!
